### ISSUE TITLE
Can poe env support $HOME or ~ , so that user can set his secret info in his HOME path 

### ISSUE THREAD

**Issue by rainmanxp** [nat-n/poethepoet#125]
**New requirements:**

I want set some secret info(such as key) in env file
but now poe only support the env file in the project path, for example:
[tool.poe]
envfile = "./repo.env"

it means my repo.env placed in project home dir, but the info in repo.env is secret, I hope put it in $HOME/repo.env

I saw the [poethepoet] now process the envfile as following:
https://github.com/nat-n/poethepoet/blob/main/poethepoet/env/cache.py
line:27
envfile_path = self._project_dir.joinpath(envfile_path_str)
![image](https://user-images.githubusercontent.com/2510527/215714185-b2b1f31f-fd84-4b20-87ee-4b4d4ed87aba.png)

The forward process is not math with my requirements, can you support it ? such as config following:
[tool.poe]
envfile = "~/repo.env"

or

[tool.poe]
envfile = "$HOME/repo.env"

**Comment by rainmanxp** [comment]
Also I can use the config to workround, but it is not a perfect solution。
[tool.poe]
envfile = "../repo.env"

**Comment by nat-n** [comment]
Hi @rainmanxp, Sure why not... 

This should do the trick: https://github.com/nat-n/poethepoet/commit/f83acf0e5364c737c84d979308d7c03dfde55322

It'll be in the next release 🙂

**Comment by nat-n** [comment]
The enhancement is shipped in [0.19.0](https://pypi.org/project/poethepoet/0.19.0/) 🙂
