### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by demetrius-mp** [nat-n/poethepoet#152]
didnt create a pull request to avoid triggering the CI, not sure if you have some guide on reporting/fixing typos.

anyways, right [here](https://github.com/nat-n/poethepoet/blob/d768ec536d602475866a8012d607a7f2dea50f2a/docs/tasks/task_types/cmd.rst?plain=1#L67) the command executed is `poe greet`, but it looks like it should be `poe clean` (see line 60 on the same file).

**Comment by nat-n** [comment]
Hi @demetrius-mp, thanks for reporting this. For documentation fixes you can make a PR straight to master, or else I'll make a note to fix this when I have some time.

I also just realized the link from the readme to the CONTRIBUTING.rst was recently broken 😖
