### ISSUE TITLE
envfile on Windows is opened with ANSI code page

### ISSUE THREAD

**Issue by rockallite** [nat-n/poethepoet#176]
Because the [envfile](https://poethepoet.natn.io/global_options.html#global-environment-variables) is opened [without an explicit encoding](https://github.com/nat-n/poethepoet/blob/c46c9c21950905af873556789637f37942670758/poethepoet/env/cache.py#L30C23-L30C23), the encoding used is [platform-dependent](https://docs.python.org/3/library/functions.html#open): [locale.getencoding()](https://docs.python.org/3/library/locale.html#locale.getencoding) is called to get the current locale encoding, which is ANSI code page on Windows by the way.

So poethepoet will complain about a UTF-8 encoded envfile with non-ASCII characters on Windows. This creates a lot of annoyance. Please fix this, by either allowing the user to specify an encoding for envfile, or opening the envfile with UTF-8 encoding by default. Thank you.

**Comment by nat-n** [comment]
Hi @rockallite, thanks for the feedback! I'll see about improving this in the next release :)

**Comment by nat-n** [comment]
Thanks again for reporting this bug. It's now fixed with [v0.24.2](https://pypi.org/project/poethepoet/0.24.2/) 🚀
