### ISSUE TITLE
Provide default poe root through env var

### ISSUE THREAD

**Issue by emanueljg** [nat-n/poethepoet#206]
There are a few environments in which it becomes very hard if not impossible to provide CLI args to get desired behavior. Would it be possible to read the desired Poe root through an env var?
```console
$ export POE_ROOT='foo'
$ poe ...
```
would then be equal to
```console
$ poe --root='foo'
```
but with the CLI options obviously taking precedence.

**Comment by nat-n** [comment]
Having a default value for the `--root` arg from the environment sounds reasonable. I suspect we'd need to make sure it doesn't collide with any env vars already used by poe (like `POE_ROOT`) to avoid unexpected behavior when for example invoking the poe CLI from within a poe task – more thought required on that question.

**Comment by nat-n** [comment]
This features is now available with [0.26.0](https://pypi.org/project/poethepoet/0.26.0/) 🚀

You can set the `POE_PROJECT_DIR` environment variable and poe will look there for the pyproject.toml
