### ISSUE TITLE
Poe uses different CLI args for working directory than Poetry

### ISSUE THREAD

**Issue by jeraymond** [nat-n/poethepoet#212]
Poetry used `-C` and `--directory` for the working directory, whereas Poe uses `--root`. It'd be nice if these were consistent. Would you be open to adding support for `-C` and `--directory` in addition to `--root` for this? If so, I'm happy to contribute a PR.

**Comment by nat-n** [comment]
Hi @jeraymond,

After thinking it over a bit I think you're right, it makes sense to align with this convention (which various unix utils also follow). 

I wouldn't want this to be a breaking change, but also wouldn't want the documentation to get noisy, so I'd say the --root option should be deprecated in the sense of being removed from the documentation but still functional.

So I'd be happy to receive a PR on this.

**Comment by nat-n** [comment]
Shipped in [https://pypi.org/project/poethepoet/0.26.0/](0.26.0) 🚀
