### ISSUE TITLE
docs recommended method fails to install as plugin at MacOS with poetry 1.8.3

### ISSUE THREAD

**Issue by mshonichev** [nat-n/poethepoet#220]
Official way to install poetry at MacOS is:

```
brew install poetry
```

that gives me poetry 1.8.3

After that installing poe as the poetry plugin with command recommended by the documentation becomes severely impossible:

```
poetry self add 'poethepoet[poetry_plugin]'  
Using version ^0.26.1 for poethepoet

Updating dependencies
Resolving dependencies... (8.7s)

Package operations: 4 installs, 20 updates, 0 removals

  - Downgrading certifi (2024.2.2 /usr/local/lib/python3.12/site-packages -> 2023.11.17): Installing...
  - Downgrading idna (3.7 -> 3.6): Installing...
  - Downgrading more-itertools (10.2.0 -> 10.1.0): Failed

...
  ERROR: Cannot uninstall more-itertools 10.2.0, RECORD file not found. Hint: The package was installed by brew.

```

Why does `poe` require older version of `more-itertools` (also `urllib`, `idna`)  in that scenario?

**Workaround**: install via pip

```
pip install 'poethepoet[poetry_plugin]'
```

goes flawlessly as DOES NOT require downgrading at all

**Comment by nat-n** [comment]
Hi @mshonichev, thanks for reporting this issue. 

I'm quite surprised that the brew installation can impact what gets installed in the poetry venv. I'll investigate a bit when I have some time. It may be that updating poethepoet's dependencies might help.

**Comment by nat-n** [comment]
Hi @mshonichev, I just looked at this again and am forced to conclude that the brew installation of poetry is a bit problematic . I didn't replicate this issue but I encountered other issues with the poetry venv created by brew being broken (as it appears to have been for you).

I would advise using the [official installer](https://python-poetry.org/docs/#installing-with-the-official-installer), which hasn't doesn't seem to have this kind of issue.

The following works aas expected for me:
```sh
curl -sSL https://install.python-poetry.org | python3 -
poetry self add 'poethepoet[poetry_plugin]'
```
