### ISSUE TITLE
Upgrade ruff?

### ISSUE THREAD

**Issue by cclauss** [nat-n/poethepoet#246]
https://github.com/nat-n/poethepoet/blob/c5841bc3ef14dab3aeea71dc89f93690948e9191/pyproject.toml#L26 vs.
https://github.com/astral-sh/ruff/releases

**Comment by nat-n** [comment]
hi @cclauss, Thanks for the suggestion and the PR. I currently have a feature branch that includes some refactors that might be hard to rebase with this kind of change, so I'll came back to this later.

**Comment by nat-n** [comment]
Done with #260
