### ISSUE TITLE
Config validation error on default environment value

### ISSUE THREAD

**Issue by DouglasBlackwood** [nat-n/poethepoet#262]
Hi!

I want to upgrade poethepoet to 0.31.0, but I get an error when I run the command `poe`.

```
$ poe
Poe the Poet - A task runner that works well with poetry.
version 0.31.0

Error: Invalid content in included file from /Users/charlylaurent/dev/engine/poe-bug-0.31.0/poe.toml
     | From: ConfigValidationError("Option 'env.HELLO' must have a value of type: str")
```

I reproduce the issue with the following configuration file `poe.toml`:

```toml
[tool.poe.executor]
type = "poetry"

[tool.poe.env]
HELLO.default = "world"
```

It seems that the `ENV.default = "something"` raises the error above.

**Comment by nat-n** [comment]
Hi @DouglasBlackwood, 

Oops! Thanks for reporting this. Here's a fix 👉 [0.31.1](https://pypi.org/project/poethepoet/0.31.1/) 🚀
