### ISSUE TITLE
Direct substitution of some global variables

### ISSUE THREAD

**Issue by AKuederle** [nat-n/poethepoet#38]
First of all, thank you for creating this tool!

I tried converting some commands to use poe and ran into a small issue. Namely, I am using a command-line tool that requires passing the path to a config file as ENV var.
Therefore, I was using a task like this:

```
{cmd = "tool", env = { CONFIG_PATH = "path/to/config.json"}}
```

This works great, if I use the absolute path to the config. However, the tool I am using does not support realitve paths to the config file (i.e. "./subdir/config.json") would not work.

Poe is aware of the current directory of the Python project. However, at the moment, it is not possible (at least I think) to directly subsititute this path into a command.

For example, what whould be awesome, if you could do something like this:

```
{cmd = "tool", env = { CONFIG_PATH = "{{POE_ROOT}}/subdir/config.json}}
```

The idea would be, that "{{POE_ROOT}}" would get replaced by poe, before the command is executed by the shell. This would be more powerful than just providing `POE_ROOT` (and others) as a global variable, as it would be independent of how different operating systems would handle variable substitution.

The "{{...}}" syntax is of course just a suggestion.

Hence, my feature request is:

- Add a simple templating syntax that is supported in the actual command strings and the env variables.
- The template strings are replaced by poe before the execution with the respective global variable (maybe simply the configured global env-vars?
- If no matching variable is found poe throws an error
- There could be a configuration to disable this functionality: e.g. `{..., disable_var_substitution= true}`

Let me know what you think of it and I would be open to give it a try :)

P.S.: I know that I could rewrite my task as a Python task to get the functionality I need, but it would be cool if there would be a way to write such tasks more easily.

**Comment by nat-n** [comment]
@AKuederle I hope this works for you! https://github.com/nat-n/poethepoet/releases/tag/v0.13.0

**Comment by AKuederle** [comment]
Awesome! thank you!
