### ISSUE TITLE
Remove the upper bound on Python 4.0

### ISSUE THREAD

**Issue by pawamoy** [nat-n/poethepoet#43]
Setting this bound forces every project that depends on yours to also set it. Reasons why it's not obviously a good thing to do: https://iscinumpy.dev/post/bound-version-constraints/ (I'll let you form your own opinion of course).

**Comment by nat-n** [comment]
Hi @pawamoy, I'm going to [plead innocent](https://github.com/nat-n/poethepoet/blob/main/pyproject.toml) on this one... unless I'm missing something?

**Comment by pawamoy** [comment]
Poetry's `python = "^3.6.2"` is equivalent to `>=3.6.2,<4.0.0` :slightly_smiling_face:

**Comment by nat-n** [comment]
Touché. And thanks for the link, it is a tricky topic and I thank you for the prompt to look into it.

It sounds like uncapping the python version might not be a bad idea (in principle).

However I just noticed that it's just as well we don't depend on ">=1.2.2" for tomli since [last week's release of 2.0.0](https://github.com/hukkin/tomli/blob/master/CHANGELOG.md#200) would have silently broken poe!

**Comment by nat-n** [comment]
That said it looks like I've fallen into the trap of viral max python version constraints, due to using pylint with poetry:

```
  The current project's Python requirement (>=3.6.2) is not compatible with some of the required packages Python requirement:
    - pylint requires Python ~=3.6, so it will not be satisfied for Python >=4.0
```

So it looks like there's nothing to be done for now (and no urgency). I'd likely accept a PR to address this in future.

**Comment by pawamoy** [comment]
Ah, I guess I'll open the same ticket at pylint then :joy: 
Alright, thanks :slightly_smiling_face:

**Comment by pawamoy** [comment]
In fact, pylint 2.12.2 already removed the cap! https://github.com/PyCQA/pylint/blob/eec287fae66f8fc514d5daa9caee46fd0e0cb6d9/setup.cfg#L53
So if you update your pylint spec to remove the cap as well, that will be one less blocker :smile: (other deps might still have the cap)

**Comment by nat-n** [comment]
You might have to keep going:

```
  SolverProblemError

  The current project's Python requirement (>=3.6.2) is not compatible with some of the required packages Python requirement:
    - astroid requires Python ~=3.6, so it will not be satisfied for Python >=4.0

  Because no versions of pylint match >2.12.2,<3.0.0
   and pylint (2.12.2) depends on astroid (>=2.9.0,<2.10), pylint (>=2.12.2,<3.0.0) requires astroid (>=2.9.0,<2.10).
  Because astroid (2.9.0) requires Python ~=3.6
   and no versions of astroid match >2.9.0,<2.10, astroid is forbidden.
  Thus, pylint is forbidden.
  So, because poethepoet depends on pylint (^2.12.2), version solving failed.
  ```

**Comment by pawamoy** [comment]
:joy:

And I shall keep going! Not released yet but [the next version of astroid will also lift the cap](https://github.com/PyCQA/astroid/blob/a9f5f97553de75717a472b05b3bbc268ea1e019e/setup.cfg#L44) :slightly_smiling_face:

**Comment by nat-n** [comment]
Looks like there's some work to be done here at some point, I'm reopening this issue.

**Comment by nat-n** [comment]
Thanks to @Parnassius for completing this task. 🚀
