### ISSUE TITLE
Importing tasks from external tasks file

### ISSUE THREAD

**Issue by kghenderson** [nat-n/poethepoet#44]
Not sure if this is already possible, but don't see it mentioned anywhere yet.

Ideally I'd like to include some tasks for my package (A) and be able to import them as local tasks (B).
Alternatively, it may be simpler to have a local tasks subdirectory (B) and copy/sync the mypackage.tasks (from A).

The challenge is that pyproject.toml is large and manually syncing these tasks can be error-prone and tedious.
This could also open the possibility of writing a script to _generate_ those tasks based on the local configuration.
While it could probably be done by editing pyproject.toml directly, a separate file would be a lot safer.

Thanks for considering.
Kevin

**Comment by nat-n** [comment]
Hi Kevin, 
@kghenderson

I'm not sure I've understood what you're describing. 

But something I have been considering is allowing tasks to be defined in a separate toml file within the same project by specifying something like `tool.poe.include = "tasks.toml"`. The use cases I had in mind were to better support having a large number of tasks, or sharing tasks between projects via a git submodule. I guess the other toml file could even be dynamically generated.

Would this work for your use case?

---

Also in case it's relevant you can edit a toml file in place the same way that poetry does using [tomlkit](https://github.com/sdispater/tomlkit)

**Comment by kghenderson** [comment]
Awesome, yes, I believe it would! :-)

**Comment by nat-n** [comment]
This feature has just been released as part of [0.12.0](https://github.com/nat-n/poethepoet/releases/tag/v0.12.0)

@kghenderson I hope it works well for you :)

**Comment by kghenderson** [comment]
That's awesome @nat-n ! Thank you so much, can't wait to try it out!

Kevin
