### ISSUE TITLE
Multiple files support.

### ISSUE THREAD

**Issue by jma** [nat-n/poethepoet#59]
It would be nice that the poet support multiple `pyproject.toml` files. When a `pyproject.toml` file exist in a cloned project, it would be nice to be able to add new commands without modifying the project. In such case I can add a config file in parent directories.

Thanks in advance.

**Comment by nat-n** [comment]
Hi @jma,

I'd be interested to hear more about your use case. 

I'm not 100% I understand, but have you seen [the include option](https://github.com/nat-n/poethepoet#load-tasks-from-another-file)?

This lets you declare that poe should also look in another file in your project for tasks. I originally implemented this with the idea of including tasks from a git submodule so it currently only works with files inside the project. However I recently realized it would also be useful to allow including files from parent directories to support sharing tasks across a mono-repo, so I intend to add support for this when I get the chance.

Of course this `include` approach requires that you specify a relative path to the tasks file, would this work for your use case? 

It sounds like what maybe you're asking for want is for poe to always scan all parent directories for more pyproject.toml files. I would hesitate to implement this kind functionality, given that it would usually be wasteful, and I feel like it would be inappropriate and kinda surprising for a tool like poe to scan around the file system looking for tasks outside of the project where its in use.
