### ISSUE TITLE
Plugin broke poetry

### ISSUE THREAD

**Issue by kbhatiya999** [nat-n/poethepoet#79]
![image](https://user-images.githubusercontent.com/47816034/178774685-2a8fc5a9-370d-4cda-9bf4-f90c531f66fb.png)

Steps to reproduce:
pip install poetry==1.2.0b2
poetry self add poetry-version-plugin
poetry self add poethepoet[poetry_plugin]

**Comment by nat-n** [comment]
Hi @kbhatiya999, thanks for reporting this.

I followed your steps with python 3.10 on macOS but was not able to reproduce the issue. I don't have immediate access to a window dev environment, so I'm going to need some help understanding what's going on here.

Could you tell me:
1. what version of python are you using?
2. does this still happen with the latest version of poetry (>=1.2.0b3) and poethepoet (>=0.15.0)?
3. what version of poetry-version-plugin does this happen with?
4. does this still happen if you don't add poetry-version-plugin?
5. does this still happen if you swap the order of adding plugins?
6. does this still happen if you comment all poe tasks in your pyproject.toml?

**Comment by ThatXliner** [comment]
Remind me again, did our Poetry plugin use the `poetry poe task` style or `poetry task` or both?

**Comment by kbhatiya999** [comment]
> Hi @kbhatiya999, thanks for reporting this.
> 
> I followed your steps with python 3.10 on macOS but was not able to reproduce the issue. I don't have immediate access to a window dev environment, so I'm going to need some help understanding what's going on here.
> 
> Could you tell me:
> 
> 1. what version of python are you using? 3.8 and 3.10.5
> 2. does this still happen with the latest version of poetry (>=1.2.0b3) and poethepoet (>=0.15.0)? Yes, 0.15.0
> 3. what version of poetry-version-plugin does this happen with? 0.1.3
> 4. does this still happen if you don't add poetry-version-plugin? Yes, but poethepoet add poetry-version-plugin anyways as a dependency.
> 5. does this still happen if you swap the order of adding plugins? Doesn't matter, to fix poetry all I had to do was pip uninstall poethepoet.
> 6. does this still happen if you comment all poe tasks in your pyproject.toml? Yes

**Comment by ThatXliner** [comment]
It seems to me that the plugin itself is breaking poetry. Just curious, what happens when you try to use Poe via Poetry plugin? Does it work?

**Comment by kbhatiya999** [comment]
> It seems to me that the plugin itself is breaking poetry. Just curious, what happens when you try to use Poe via Poetry plugin? Does it work?

I think so too.
I am also curious. I will try.

**Comment by nat-n** [comment]
@kbhatiya999 thanks for the details. Also curious whether invoking poe tasks via the plugin works.

@ThatXliner The plugin is configurable; by default it registers a `poe` command, but  you can make it use another name or just register tasks directly: https://github.com/nat-n/poethepoet#configuring-the-plugin 

I'll see where I get with trying to reproduce this, though I might need to install and setup a Windows VM :/ Any help with debugging would be appreciated.

**Comment by nat-n** [comment]
@kbhatiya999  Also curious if the issue still occurs if you install the plugin with `pip install poethepoet[poetry_plugin]` instead?

**Comment by kbhatiya999** [comment]
If you have good amount of storage on your Mac check this out :
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by kbhatiya999** [comment]
![image](https://user-images.githubusercontent.com/47816034/179369317-cfc68090-fe12-4cf6-b3f3-f725aed39369.png)
I figured out that 1 in the screenshot (check 1st message of the thread) is from Intex Error 1

  File "C:\Users\Kashish\AppData\Local\pypoetry\Cache\virtualenvs\poetry-bugs-FSWo2tWM-py3.8\lib\site-packages\poethepoet\config.py", line 223, in find_pyproject_toml
    maybe_result = maybe_result.parents[1].joinpath(self.TOML_NAME).resolve()
  File "C:\Users\Kashish\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 621, in __getitem__
    raise IndexError(idx)
IndexError: 1

How to reproduce: run "poetry" command from a directory without "pyproject.toml"  in it or any of it's parent directory.

**Comment by nat-n** [comment]
Thanks @kbhatiya999, that's very interesting. How poetry handles errors is weird... also poetry probably should not break when a plugin is broken... that's another issue. The plugin should also be more careful not to break!

I think the root cause is that the logic [on this line](https://github.com/nat-n/poethepoet/blob/main/poethepoet/config.py#L218) doesn't work the same on windows.

I'll try post a fix tomorrow. I hope you'll be able to help with verifying it?

**Comment by kbhatiya999** [comment]
@nat-n I will do everything I can.

**Comment by kbhatiya999** [comment]
@nat-n should we create issue in poetry repo as you mentioned?

**Comment by nat-n** [comment]
@kbhatiya999 I've created [this PR](https://github.com/nat-n/poethepoet/pull/81/files) that I think should fix the issue.

I'm not sure if you can install a plugin directly into poetry from an arbitrary source, but I've found this works to install the fix alongside poetry with pip: `pip install git+https://github.com/nat-n/poethepoet.git@d217603`.

Yes, I think it's worth creating that issue for poetry. Let me know if you do, otherwise I will.

**Comment by kbhatiya999** [comment]
> @kbhatiya999 I've created [this PR](https://github.com/nat-n/poethepoet/pull/81/files) that I think should fix the issue.
> 
> I'm not sure if you can install a plugin directly into poetry from an arbitrary source, but I've found this works to install the fix alongside poetry with pip: `pip install git+https://github.com/nat-n/poethepoet.git@d217603`.
> 
> Yes, I think it's worth creating that issue for poetry. Let me know if you do, otherwise I will.
> 
> Also for my understanding, could you tell me what this shows on windows?
> 
> ```shell
> python -c "from pathlib import Path; print(list(Path('.').resolve().parents)[-1])"
> ```

![image](https://user-images.githubusercontent.com/47816034/179400985-6064bc13-9ee3-4cee-b7c5-0f299d4f22ac.png)

C:\

Please go ahead and create the issue since you understand it better than me.

**Comment by kbhatiya999** [comment]
I confirm that poetry is no longer crashing. 

```
poetry self add git+https://github.com/nat-n/poethepoet.git@d217603[poetry_plugin]
```

**Comment by ThatXliner** [comment]
Should this be closed?

**Comment by nat-n** [comment]
Hi @khanfarhan10,

From the error message it looks like the issue it to do with the python version in your environment. Python 3.8 is end of life, and not supported by the most recent versions of Poe the Poet.

What's surprising is that the `poetry self add` command choses an incompatible version of the poethepoet distribution, which then of course fails to install.

The best advice I can give in this situation is either to upgrade to a recent version of python, or specify version 0.30.0 of poethepoet which was the last one to support python 3.8. I expect the following should work for you
```sh
poetry self add 'poethepoet[poetry_plugin]'==0.30.0
```
