### ISSUE TITLE
flag expects arguments

### ISSUE THREAD

**Issue by twoertwein** [nat-n/poethepoet#80]
Based on the readme, a flag is defined by `type = "bool"`. It seems that flags still expect one arguments:

```py
[tool.poetry]
name = "test"
version = "0.0.1"
description = "test"
authors = ["test"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"

[tool.poetry.dev-dependencies]
poethepoet = ">=0.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks.test]
help = "Run tests"
script = "scripts.test:test(flag)"

    [[tool.poe.tasks.test.args]]
    help = "set flag"
    name = "flag"
    default = false
    type = "bool"
```
```sh
$ poe test --flag
usage: poe test [--flag FLAG]
poe test: error: argument --flag: expected one argument
```

**Comment by nat-n** [comment]
Hi @twoertwein , thanks for reporting this.

I see three issues here. The first is that the the type is meant to be called "boolean". So if you update the type option to `type = "boolean"` then it should work as expected. 

The other two issues are that poe should tell you that, and that the documentation gets this wrong in one place. I'll post a fix shortly, but I hope this information is enough to unblock you :)

**Comment by twoertwein** [comment]
Thank you! Chaning bool to boolean works :)
