### ISSUE TITLE
How to buy you a coffee?

### ISSUE THREAD

**Issue by JosXa** [nat-n/poethepoet#9]
I've been on a GitHub issues research spree today looking for a viable alternative to Makefiles with their archaic syntax, checking out [doit](https://github.com/pydoit/doit) and [fabfile](https://docs.fabfile.org/en/2.5/) in the process and making some detours over other task runners, however none of them really fit my definition of modern Python or just didn't play nice with Poetry... and then eventually I came across your post in the Poetry repo and gotta say, this is *exactly* what I've been looking for. It's similar to npm scripts, easy to use, comes with all the batteries included that I need and worked perfectly out of the box. It looks like there finally is a solution that integrates well with Poetry without the learning curve that other tools bring...

Man, kudos to you, you made my day :) 

Be sure to create some donations page so I can invite you to a few beers!
(And feel free to quote this in your README if you want)

**Comment by nat-n** [comment]
Thanks for the kind words, that's very encouraging.

**Comment by nat-n** [comment]
@JosXa Also thanks for the idea. I found a solution.

[![alt text](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "buy me a coffee")](https://www.buymeacoffee.com/natn)
